version: 2

jobs:
  build-dependencies:
    docker:
      - image: circleci/node:9.2.1
    working_directory: ~/codesandbox-client
    steps:
      - checkout
      - restore_cache:
          key: v2-dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: v2-dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
            - ./packages/app/node_modules
            - ./packages/codesandbox-api/node_modules
            - ./packages/common/node_modules
            - ./packages/homepage/node_modules
            - ~/.yarn-cache
      - run:
          name: Build
          command: yarn build:dependents
      - save_cache:
          key: v2-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/codesandbox-client

  build-prod:
    docker:
      - image: circleci/node:9.2.1
    working_directory: ~/codesandbox-client
    steps:
      - restore_cache:
          key: v2-repo-{{ .Environment.CIRCLE_SHA1 }}
      # We do this to compare sizes from these builds with master
      - restore_cache:
          key: v2-prod-app-build-cache-master
      - run:
          name: Build Application
          command: yarn build:prod
      - save_cache:
          key: v2-prod-app-build-cache-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ./packages/app/www
      - save_cache:
          key: v2-prod-build-cache-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ./www
      - store_artifacts:
          path: ./www
          destination: www

  test-integrations:
    docker:
      - image: codesandbox/node-puppeteer
    working_directory: ~/codesandbox-client
    steps:
      - restore_cache:
          key: v2-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Start Test Server
          command: yarn start:test
          background: true
      - run:
          name: Test Integrations
          command: |
            sleep 6
            yarn test:integrations
      - store_artifacts:
          path: packages/app/integration-tests/tests/__image_snapshots__/__diff_output__
          destination: image_snapshot_diff

  test-jest:
    docker:
      - image: circleci/node:9.2.1
    working_directory: ~/codesandbox-client
    steps:
      - restore_cache:
          key: v2-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Test
          command: yarn test

  lint:
    docker:
      - image: circleci/node:9.2.1
    working_directory: ~/codesandbox-client
    steps:
      - restore_cache:
          key: v2-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Lint
          command: yarn lint

  deploy:
    docker:
      - image: circleci/node:9.2.1
    working_directory: ~/codesandbox-client
    steps:
      - restore_cache:
          key: v2-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v2-prod-build-cache-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - add_ssh_keys:
          fingerprints:
            - "f7:f1:e6:60:96:24:d9:cd:1b:8b:c0:34:e7:ee:fa:82"
      - run:
          name: Add key to known_hosts
          command: echo "ssh.codesandbox.io ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBKyKbuMPJSETTyPRRJVOeC5I8j7wyUMW8HYheg7cN71eKTuw55tkoygxI59BvNi/CAyCnRT5LnxZhvrq9nSlPYc=" >> ~/.ssh/known_hosts
      - deploy:
          command: sh ./deploy.sh

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-dependencies
      - test-integrations:
          requires:
            - build-dependencies
      - test-jest:
          requires:
            - build-dependencies
      - lint:
          requires:
            - build-dependencies
      - build-prod:
          requires:
            - build-dependencies
      - hold:
          type: approval
          filters:
            branches:
              only: master
          requires:
            - build-prod
            - lint
            - test-integrations
            - test-jest
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - hold



